name: nrb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - gdal>=3.4.1
  - click
  - lxml
  - pip
  - pystac
  - scipy
  - pyroSAR>=0.16.2
  - pip:
      - s1etad @ git+https://gitlab.com/s1-etad/s1-etad.git
      - s1etad_tools @ git+https://gitlab.com/s1-etad/sandbox-etad-slc-correction.git
