name: nrb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal>=3.4.1
  - click
  - lxml
  - pip
  - pystac
  - scipy
  - spatialist>=0.10.1
  - pip:
    - pyroSAR @ git+https://github.com/johntruckenbrodt/pyroSAR.git
