name: nrb_env
channels:
  - conda-forge
  - defaults
  - s1-etad
dependencies:
  - python>=3.8
  - gdal>=3.5.0
  - click>=7.1.0
  - lxml
  - pip
  - pystac
  - scipy
  - pyroSAR>=0.20.0
  - spatialist>=0.12.0
  - s1etad>=0.5.3
  - s1etad_tools>=0.8.1
